using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Shared.Atmos;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.HealthAnalyzer.UI;

#pragma warning disable CS0618 // DamageGroupPrototype разрешён для логической группировки урона в UI.

/// <summary>
/// Displays the server-authoritative diagnostic snapshot used by health analyzers and cryo pods.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private const float RevealDuration = 0.18f;

    private static readonly ResPath AnalyzerRsi = new("/Textures/Objects/Devices/health_analyzer.rsi");

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _sprite;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly Dictionary<ProtoId<DamageGroupPrototype>, DamageGroupDisplay> _damageGroups = [];
    private readonly Dictionary<ProtoId<ReagentPrototype>, RichTextLabel> _reagentRows = [];
    private readonly List<(ReagentPrototype Prototype, FixedPoint2 Quantity)> _reagentBuffer = [];

    private float _revealProgress;
    private bool _revealing;
    private bool _hasPatient;

    /// <summary>
    /// Controls whether this reusable view displays its own empty damage message.
    /// </summary>
    public bool ShowNoDamageText { get; set; } = true;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _sprite = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        BuildDamageGroups();
    }

    /// <summary>
    /// Updates the displayed patient snapshot without rebuilding stable diagnostic rows.
    /// </summary>
    public void Populate(HealthAnalyzerUiState state)
    {
        if (state.TargetEntity == null)
        {
            ShowNoPatient();
            return;
        }

        NoPatientContainer.Visible = false;
        PatientDataContainer.Visible = true;

        if (!_hasPatient)
            StartReveal();

        _hasPatient = true;

        UpdateScanMode(state.ScanMode);
        UpdatePortrait(state);

        NameLabel.Text = state.PatientName ?? Loc.GetString("health-analyzer-window-entity-unknown-text");
        SpeciesLabel.Text = state.Species is { } speciesId && _prototypes.TryIndex(speciesId, out var species)
            ? Loc.GetString(species.Name)
            : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        StatusLabel.Text = state.MobState is { } mobState
            ? GetStatus(mobState)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        SetStatusStyle(StatusLabel, GetMobStatusFactor(state.MobState));

        TemperatureLabel.Text = float.IsFinite(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        UpdatePercentage(BloodRow, BloodBar, BloodLabel,
            float.IsFinite(state.BloodLevel) ? state.BloodLevel : null,
            hideWhenUnknown: false);
        UpdatePercentage(HungerRow, HungerBar, HungerLabel,
            state.HungerLevel is { } hunger && float.IsFinite(hunger) ? hunger / 100f : null);
        UpdatePercentage(ThirstRow, ThirstBar, ThirstLabel,
            state.ThirstLevel is { } thirst && float.IsFinite(thirst) ? thirst / 100f : null);

        UnrevivableAlert.Visible = state.Unrevivable == true;
        BleedingAlert.Visible = state.Bleeding == true;
        AlertsContainer.Visible = UnrevivableAlert.Visible || BleedingAlert.Visible;

        UpdateDamage(state.Damage);
        UpdateReagents(state.Reagents);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_revealing)
            return;

        _revealProgress = Math.Min(1f, _revealProgress + args.DeltaSeconds / RevealDuration);
        var eased = 1f - MathF.Pow(1f - _revealProgress, 3f);
        PatientDataContainer.ModulateSelfOverride = Color.White.WithAlpha(0.35f + eased * 0.65f);

        if (_revealProgress < 1f)
            return;

        PatientDataContainer.ModulateSelfOverride = null;
        _revealing = false;
    }

    private void ShowNoPatient()
    {
        NoPatientContainer.Visible = true;
        PatientDataContainer.Visible = false;
        PatientDataContainer.ModulateSelfOverride = null;
        SpriteView.Visible = false;
        NoDataTex.Visible = true;
        _hasPatient = false;
        _revealing = false;
    }

    private void StartReveal()
    {
        _revealProgress = 0f;
        _revealing = true;
        PatientDataContainer.ModulateSelfOverride = Color.White.WithAlpha(0.35f);
    }

    private void UpdateScanMode(bool? scanMode)
    {
        ScanModeLabel.Text = scanMode switch
        {
            true => Loc.GetString("health-analyzer-window-scan-mode-active"),
            false => Loc.GetString("health-analyzer-window-scan-mode-inactive"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
        SetStatusStyle(ScanModeLabel, scanMode switch { true => 1f, false => 0.25f, _ => 0.5f });
    }

    private void UpdatePortrait(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        var showSprite = target != null && state.ScanMode == true;

        if (showSprite)
            SpriteView.SetEntity(target!.Value);

        SpriteView.Visible = showSprite;
        NoDataTex.Visible = !showSprite;
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private static float GetMobStatusFactor(MobState? mobState)
    {
        return mobState switch
        {
            MobState.Alive => 1f,
            MobState.Critical => 0.25f,
            MobState.Dead => 0f,
            _ => 0.5f,
        };
    }

    private static void UpdatePercentage(
        BoxContainer row,
        ProgressBar bar,
        Label label,
        float? value,
        bool hideWhenUnknown = true)
    {
        row.Visible = value.HasValue || !hideWhenUnknown;
        bar.Visible = value.HasValue;

        if (!value.HasValue)
        {
            label.Text = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            return;
        }

        var fraction = Math.Clamp(value.Value, 0f, 1f);
        bar.Value = fraction;
        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        ((StyleBoxFlat) bar.ForegroundStyleBoxOverride).BackgroundColor = Palettes.Status.GetStatusColor(fraction);
        label.Text = $"{value.Value * 100f:F1} %";
    }

    private void BuildDamageGroups()
    {
        var groups = new List<DamageGroupPrototype>(_prototypes.EnumeratePrototypes<DamageGroupPrototype>());
        groups.Sort((left, right) => string.Compare(
            left.LocalizedName,
            right.LocalizedName,
            StringComparison.CurrentCulture));

        foreach (var group in groups)
        {
            var root = new PanelContainer
            {
                Visible = false,
                StyleClasses = { StyleClass.BackgroundPanel },
            };
            var content = new BoxContainer
            {
                Margin = new Thickness(6, 4),
                Orientation = LayoutOrientation.Vertical,
            };
            var heading = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var title = new Label { HorizontalExpand = true };

            heading.AddChild(new TextureRect
            {
                SetSize = new Vector2(24, 24),
                Texture = GetTexture(group.ID.ToLowerInvariant()),
            });
            heading.AddChild(title);
            content.AddChild(heading);

            var types = new Dictionary<ProtoId<DamageTypePrototype>, Label>();
            foreach (var typeId in group.DamageTypes)
            {
                var label = new Label
                {
                    Visible = false,
                    Margin = new Thickness(28, 0, 0, 0),
                    StyleClasses = { StyleClass.LabelSubText },
                };
                content.AddChild(label);
                types[typeId] = label;
            }

            root.AddChild(content);
            GroupsContainer.AddChild(root);
            _damageGroups[group.ID] = new DamageGroupDisplay(root, title, types);
        }
    }

    private void UpdateDamage(IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damage)
    {
        var totalDamage = FixedPoint2.Zero;
        foreach (var amount in damage.Values)
        {
            if (amount > 0)
                totalDamage += amount;
        }

        foreach (var (groupId, display) in _damageGroups)
        {
            var group = _prototypes.Index(groupId);
            var groupDamage = FixedPoint2.Zero;

            foreach (var (typeId, label) in display.Types)
            {
                var visible = damage.TryGetValue(typeId, out var amount) && amount > 0;
                label.Visible = visible;
                if (!visible)
                    continue;

                groupDamage += amount;
                label.Text = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index(typeId).LocalizedName),
                    ("amount", amount));
            }

            display.Root.Visible = groupDamage > 0;
            if (groupDamage <= 0)
                continue;

            display.Title.Text = Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", group.LocalizedName),
                ("amount", groupDamage));
        }

        NoDamageLabel.Visible = ShowNoDamageText && totalDamage <= 0;
        DamageLabel.Text = Loc.GetString("health-analyzer-window-damage-total", ("amount", totalDamage));
        SetStatusStyle(DamageLabel, 1f - Math.Clamp(totalDamage.Float() / 100f, 0f, 1f));
    }

    private void UpdateReagents(IReadOnlyList<ReagentQuantity> reagents)
    {
        _reagentBuffer.Clear();
        foreach (var reagent in reagents)
        {
            if (_prototypes.TryIndex<ReagentPrototype>(reagent.Reagent.Prototype, out var prototype))
                _reagentBuffer.Add((prototype, reagent.Quantity));
        }

        _reagentBuffer.Sort((left, right) => string.Compare(
            left.Prototype.LocalizedName,
            right.Prototype.LocalizedName,
            StringComparison.CurrentCulture));

        if (ReagentSetChanged())
            RebuildReagentRows();

        foreach (var (prototype, quantity) in _reagentBuffer)
        {
            var message = new FormattedMessage();
            message.PushColor(prototype.SubstanceColor);
            message.AddText("● ");
            message.Pop();
            message.AddText(Loc.GetString(
                "health-analyzer-window-reagents-entry",
                ("reagent", prototype.LocalizedName),
                ("amount", quantity)));
            _reagentRows[prototype.ID].SetMessage(message);
        }

        NoReagentsLabel.Visible = _reagentBuffer.Count == 0;
        ReagentsListContainer.Visible = _reagentBuffer.Count > 0;
        ReagentsCountLabel.Text = Loc.GetString(
            "health-analyzer-window-reagents-count",
            ("count", _reagentBuffer.Count));
    }

    private bool ReagentSetChanged()
    {
        if (_reagentRows.Count != _reagentBuffer.Count)
            return true;

        foreach (var (prototype, _) in _reagentBuffer)
        {
            if (!_reagentRows.ContainsKey(prototype.ID))
                return true;
        }

        return false;
    }

    private void RebuildReagentRows()
    {
        ReagentsListContainer.RemoveAllChildren();
        _reagentRows.Clear();

        foreach (var (prototype, _) in _reagentBuffer)
        {
            var label = new RichTextLabel();
            ReagentsListContainer.AddChild(label);
            _reagentRows[prototype.ID] = label;
        }
    }

    private Texture GetTexture(string stateId)
    {
        var sprite = new SpriteSpecifier.Rsi(AnalyzerRsi, stateId);
        var rsi = _cache.GetResource<RSIResource>(AnalyzerRsi).RSI;

        if (!rsi.TryGetState(stateId, out _))
            sprite = new SpriteSpecifier.Rsi(AnalyzerRsi, "unknown");

        return _sprite.Frame0(sprite);
    }

    private static void SetStatusStyle(Label label, float factor)
    {
        label.RemoveStyleClass(StyleClass.StatusGood);
        label.RemoveStyleClass(StyleClass.StatusOkay);
        label.RemoveStyleClass(StyleClass.StatusWarning);
        label.RemoveStyleClass(StyleClass.StatusBad);
        label.RemoveStyleClass(StyleClass.StatusCritical);

        label.AddStyleClass(factor switch
        {
            >= 0.875f => StyleClass.StatusGood,
            >= 0.625f => StyleClass.StatusOkay,
            >= 0.375f => StyleClass.StatusWarning,
            >= 0.125f => StyleClass.StatusBad,
            _ => StyleClass.StatusCritical,
        });
    }

    private sealed class DamageGroupDisplay(
        PanelContainer root,
        Label title,
        Dictionary<ProtoId<DamageTypePrototype>, Label> types)
    {
        public readonly PanelContainer Root = root;
        public readonly Label Title = title;
        public readonly Dictionary<ProtoId<DamageTypePrototype>, Label> Types = types;
    }
}

#pragma warning restore CS0618
